version: '3'

services:

  blogging:
    build: .
    container_name: blogging
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/blogging?schema=public
    ports:
      - 127.0.0.1:5000:5000
      - "[::1]:5000:5000"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
      - "[::1]:5432:5432"
